export const movies = [
    {
      id: 1,
      title: "Avatar",
      year: "2009",
      rated: "PG-13",
      released: "18 Dec 2009",
      runtime: "162 min",
      genre: "Action, Adventure, Fantasy",
      director: "James Cameron",
      writer: "James Cameron",
      actors: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
      plot: "A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
      language: "English, Spanish",
      country: "USA, UK",
      awards: "Won 3 Oscars. Another 80 wins & 121 nominations.",
      poster: "http://ia.media-imdb.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_SX300.jpg",
      metascore: "83",
      imdbRating: "7.9",
      imdbVotes: "890,617",
      imdbID: "tt0499549",
      type: "movie",
      response: "True",
      images: [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjEyOTYyMzUxNl5BMl5BanBnXkFtZTcwNTg0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BNzM2MDk3MTcyMV5BMl5BanBnXkFtZTcwNjg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY2ODQ3NjMyMl5BMl5BanBnXkFtZTcwODg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMxOTEwNDcxN15BMl5BanBnXkFtZTcwOTg0MTUzNA@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYxMDg1Nzk1MV5BMl5BanBnXkFtZTcwMDk0MTUzNA@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
      ]
    },
    {
      id: 2,
      title: "I Am Legend",
      year: "2007",
      rated: "PG-13",
      released: "14 Dec 2007",
      runtime: "101 min",
      genre: "Drama, Horror, Sci-Fi",
      director: "Francis Lawrence",
      writer: "Mark Protosevich (screenplay), Akiva Goldsman (screenplay), Richard Matheson (novel), John William Corrington, Joyce Hooper Corrington",
      actors: "Will Smith, Alice Braga, Charlie Tahan, Salli Richardson-Whitfield",
      plot: "Years after a plague kills most of humanity and transforms the rest into monsters, the sole survivor in New York City struggles valiantly to find a cure.",
      language: "English",
      country: "USA",
      awards: "9 wins & 21 nominations.",
      poster: "http://ia.media-imdb.com/images/M/MV5BMTU4NzMyNDk1OV5BMl5BanBnXkFtZTcwOTEwMzU1MQ@@._V1_SX300.jpg",
      metascore: "65",
      imdbRating: "7.2",
      imdbVotes: "533,874",
      imdbID: "tt0480249",
      type: "movie",
      response: "True",
      images: [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI0NTI4NjE3NV5BMl5BanBnXkFtZTYwMDA0Nzc4._V1_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTIwMDg2MDU4M15BMl5BanBnXkFtZTYwMTA0Nzc4._V1_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDM1OTU5OV5BMl5BanBnXkFtZTYwMjA0Nzc4._V1_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0MTI2NjMzMzFeQTJeQWpwZ15BbWU2MDMwNDc3OA@@._V1_.jpg"
      ]
    },
    {
      id: 3,
      title: "300",
      year: "2006",
      rated: "R",
      released: "09 Mar 2007",
      runtime: "117 min",
      genre: "Action, Drama, Fantasy",
      director: "Zack Snyder",
      writer: "Zack Snyder (screenplay), Kurt Johnstad (screenplay), Michael Gordon (screenplay), Frank Miller (graphic novel), Lynn Varley (graphic novel)",
      actors: "Gerard Butler, Lena Headey, Dominic West, David Wenham",
      plot: "King Leonidas of Sparta and a force of 300 men fight the Persians at Thermopylae in 480 B.C.",
      language: "English",
      country: "USA",
      awards: "16 wins & 42 nominations.",
      poster: "http://ia.media-imdb.com/images/M/MV5BMjAzNTkzNjcxNl5BMl5BanBnXkFtZTYwNDA4NjE3._V1_SX300.jpg",
      metascore: "52",
      imdbRating: "7.7",
      imdbVotes: "611,046",
      imdbID: "tt0416449",
      type: "movie",
      response: "True",
      images: [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMwNTg5MzMwMV5BMl5BanBnXkFtZTcwMzA2NTIyMw@@._V1_SX1777_CR0,0,1777,937_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQwNTgyNTMzNF5BMl5BanBnXkFtZTcwNDA2NTIyMw@@._V1_SX1777_CR0,0,1777,935_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0MjQzOTEwMV5BMl5BanBnXkFtZTcwMzE2NTIyMw@@._V1_SX1777_CR0,0,1777,947_AL_.jpg"
      ]
    },
    {
      id: 4,
      title: "The Avengers",
      year: "2012",
      rated: "PG-13",
      released: "04 May 2012",
      runtime: "143 min",
      genre: "Action, Sci-Fi, Thriller",
      director: "Joss Whedon",
      writer: "Joss Whedon (screenplay), Zak Penn (story), Joss Whedon (story)",
      actors: "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth",
      plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are to stop the mischievous Loki and his alien army from enslaving humanity.",
      language: "English, Russian",
      country: "USA",
      awards: "Nominated for 1 Oscar. Another 34 wins & 75 nominations.",
      poster: "http://ia.media-imdb.com/images/M/MV5BMTk2NTI1MTU4N15BMl5BanBnXkFtZTcwODg0OTY0Nw@@._V1_SX300.jpg",
      metascore: "69",
      imdbRating: "8.1",
      imdbVotes: "1,003,301",
      imdbID: "tt0848228",
      type: "movie",
      response: "True",
      images: [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0NjY0NzE4OTReQTJeQWpwZ15BbWU3MDczODg2Nzc@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE1MzEzMjcyM15BMl5BanBnXkFtZTcwNDM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjMwMzM2MTg1M15BMl5BanBnXkFtZTcwNjM4ODY3Nw@@._V1_SX1777_CR0,0,1777,999_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTY3NDkzOV5BMl5BanBnXkFtZTcwNzg4ODY3Nw@@._V1_SX1500_CR0,0,1500,999_AL_.jpg"
      ]
    },
    {
      id: 5,
      title: "The Wolf of Wall Street",
      year: "2013",
      rated: "R",
      released: "25 Dec 2013",
      runtime: "180 min",
      genre: "Biography, Comedy, Crime",
      director: "Martin Scorsese",
      writer: "Terence Winter (screenplay), Jordan Belfort (book)",
      actors: "Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey",
      plot: "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.",
      language: "English, French",
      country: "USA",
      awards: "Nominated for 5 Oscars. Another 35 wins & 154 nominations.",
      poster: "http://ia.media-imdb.com/images/M/MV5BMTk0MDY3NjYxMF5BMl5BanBnXkFtZTgwNjAyMDMzMDE@._V1_SX300.jpg",
      metascore: "75",
      imdbRating: "8.2",
      imdbVotes: "786,985",
      imdbID: "tt0993846",
      type: "movie",
      response: "True",
      images: [
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5OTQ0NDg3Ml5BMl5BanBnXkFtZTgwNjAxODg4MDE@._V1_SY1000_CR0,0,1602,1000_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMjAxOTg5Mjg3OF5BMl5BanBnXkFtZTgwNjAyMDMzMDE@._V1_SY1000_CR0,0,1602,1000_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc5MDI1NTIxM15BMl5BanBnXkFtZTgwNjAxODg4MDE@._V1_SY1000_CR0,0,1602,1000_AL_.jpg",
        "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwOTQ5MTY1MF5BMl5BanBnXkFtZTgwNjAyMDMzMDE@._V1_SY1000_CR0,0,1602,1000_AL_.jpg"
      ]
    }
  ];
  